// Code generated by protoc-gen-go. DO NOT EDIT.
// source: odirect.proto

/*
Package service is a generated protocol buffer package.

It is generated from these files:
	odirect.proto

It has these top-level messages:
	CallbackRequest
	Callback
*/
package service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CallbackRequest struct {
	ApiKey string `protobuf:"bytes,1,opt,name=api_key,json=apiKey" json:"api_key,omitempty"`
	Tag    string `protobuf:"bytes,2,opt,name=tag" json:"tag,omitempty"`
}

func (m *CallbackRequest) Reset()                    { *m = CallbackRequest{} }
func (m *CallbackRequest) String() string            { return proto.CompactTextString(m) }
func (*CallbackRequest) ProtoMessage()               {}
func (*CallbackRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CallbackRequest) GetApiKey() string {
	if m != nil {
		return m.ApiKey
	}
	return ""
}

func (m *CallbackRequest) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

type Callback struct {
	Tag   string `protobuf:"bytes,1,opt,name=tag" json:"tag,omitempty"`
	Code  string `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`
	Error string `protobuf:"bytes,3,opt,name=error" json:"error,omitempty"`
}

func (m *Callback) Reset()                    { *m = Callback{} }
func (m *Callback) String() string            { return proto.CompactTextString(m) }
func (*Callback) ProtoMessage()               {}
func (*Callback) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Callback) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *Callback) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Callback) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*CallbackRequest)(nil), "odirect.service.CallbackRequest")
	proto.RegisterType((*Callback)(nil), "odirect.service.Callback")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ODirect service

type ODirectClient interface {
	AwaitCallback(ctx context.Context, in *CallbackRequest, opts ...grpc.CallOption) (*Callback, error)
}

type oDirectClient struct {
	cc *grpc.ClientConn
}

func NewODirectClient(cc *grpc.ClientConn) ODirectClient {
	return &oDirectClient{cc}
}

func (c *oDirectClient) AwaitCallback(ctx context.Context, in *CallbackRequest, opts ...grpc.CallOption) (*Callback, error) {
	out := new(Callback)
	err := grpc.Invoke(ctx, "/odirect.service.ODirect/AwaitCallback", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ODirect service

type ODirectServer interface {
	AwaitCallback(context.Context, *CallbackRequest) (*Callback, error)
}

func RegisterODirectServer(s *grpc.Server, srv ODirectServer) {
	s.RegisterService(&_ODirect_serviceDesc, srv)
}

func _ODirect_AwaitCallback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ODirectServer).AwaitCallback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/odirect.service.ODirect/AwaitCallback",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ODirectServer).AwaitCallback(ctx, req.(*CallbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ODirect_serviceDesc = grpc.ServiceDesc{
	ServiceName: "odirect.service.ODirect",
	HandlerType: (*ODirectServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AwaitCallback",
			Handler:    _ODirect_AwaitCallback_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "odirect.proto",
}

func init() { proto.RegisterFile("odirect.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 188 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4f, 0xc9, 0x2c,
	0x4a, 0x4d, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x87, 0x71, 0x8b, 0x53, 0x8b,
	0xca, 0x32, 0x93, 0x53, 0x95, 0x6c, 0xb8, 0xf8, 0x9d, 0x13, 0x73, 0x72, 0x92, 0x12, 0x93, 0xb3,
	0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0xc4, 0xb9, 0xd8, 0x13, 0x0b, 0x32, 0xe3, 0xb3,
	0x53, 0x2b, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xd8, 0x12, 0x0b, 0x32, 0xbd, 0x53, 0x2b,
	0x85, 0x04, 0xb8, 0x98, 0x4b, 0x12, 0xd3, 0x25, 0x98, 0xc0, 0x82, 0x20, 0xa6, 0x92, 0x1b, 0x17,
	0x07, 0x4c, 0x37, 0x4c, 0x96, 0x11, 0x2e, 0x2b, 0x24, 0xc4, 0xc5, 0x92, 0x9c, 0x9f, 0x92, 0x0a,
	0xd5, 0x00, 0x66, 0x0b, 0x89, 0x70, 0xb1, 0xa6, 0x16, 0x15, 0xe5, 0x17, 0x49, 0x30, 0x83, 0x05,
	0x21, 0x1c, 0xa3, 0x48, 0x2e, 0x76, 0x7f, 0x17, 0xb0, 0xc3, 0x84, 0xfc, 0xb8, 0x78, 0x1d, 0xcb,
	0x13, 0x33, 0x4b, 0xe0, 0xe6, 0x2a, 0xe8, 0xa1, 0xb9, 0x59, 0x0f, 0xcd, 0xc1, 0x52, 0x92, 0x38,
	0x55, 0x28, 0x31, 0x38, 0x71, 0x46, 0xb1, 0x43, 0x45, 0x93, 0xd8, 0xc0, 0x61, 0x60, 0x0c, 0x08,
	0x00, 0x00, 0xff, 0xff, 0xb8, 0x0b, 0x09, 0x87, 0x14, 0x01, 0x00, 0x00,
}
